version: '2'
services:        
    test:
        image: test/spring5boot2fabricdocker:1.0
        container_name: test
        ports:
            - 3001:8080
        networks: 
            - network-demo

networks: 
    network-demo:
        driver: bridge